apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql.fullname" . }}-configmap
  labels:
    app: {{ include "proxysql.name" . }}
    app.kubernetes.io/name: {{ include "proxysql.name" . }}
    helm.sh/chart: {{ include "proxysql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (tpl ( .Files.Glob "conf/*" ).AsConfig . ) | indent 4 }}
