apiVersion: v1
kind: Service
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    app: {{ include "proxysql.name" . }}
    app.kubernetes.io/name: {{ include "proxysql.name" . }}
    helm.sh/chart: {{ include "proxysql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: proxysql-admin
      port: {{ .Values.service.admin.port }}
      targetPort: {{ .Values.service.admin.port }}
      protocol: TCP
    - name: proxysql-mysql
      port: {{ .Values.service.mysql.port }}
      targetPort: {{ .Values.service.mysql.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "proxysql.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

