apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proxysql.fullname" . }}
  labels:
    app: {{ include "proxysql.name" . }}
    app.kubernetes.io/name: {{ include "proxysql.name" . }}
    helm.sh/chart: {{ include "proxysql.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "proxysql.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "proxysql.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: proxysql-config
              mountPath: /etc/proxysql.cnf
              subPath: proxysql.cnf
          ports:
            - containerPort: 6603
              name: proxysql-mysql
            - containerPort: 6032
              name: proxysql-admin
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{- toYaml .Values.resources | indent 12 }}
      volumes:
        - name: proxysql-config
          configMap:
            name: {{ include "proxysql.fullname" . }}-configmap
